export const lottieDictionary: Record<string, Record<string, string>> = {
  FEMALE: {
    ENFJ: 'wo_enfj',
    ENFP: 'wo_enfp',
    ENTJ: 'wo_entj',
    ENTP: 'wo_entp',
    ESFJ: 'wo_esfj',
    ESFP: 'wo_esfp',
    ESTJ: 'wo_estj',
    ESTP: 'wo_estp',
    INFJ: 'wo_infj',
    INFP: 'wo_infp',
    INTJ: 'wo_intj',
    INTP: 'wo_intp',
    ISFJ: 'wo_isfj',
    ISFP: 'wo_isfp',
    ISTJ: 'wo_istj',
    ISTP: 'wo_istp',
  },
  MALE: {
    ENFJ: 'man_enfj',
    ENFP: 'man_enfp',
    ENTJ: 'man_entj',
    ENTP: 'man_entp',
    ESFJ: 'man_esfj',
    ESFP: 'man_esfp',
    ESTJ: 'man_estj',
    ESTP: 'man_estp',
    INFJ: 'man_infj',
    INFP: 'man_infp',
    INTJ: 'man_intj',
    INTP: 'man_intp',
    ISFJ: 'man_isfj',
    ISFP: 'man_isfp',
    ISTJ: 'man_istj',
    ISTP: 'man_istp',
  },
};
